[package]
name = "malakal-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malakal-widget = { path = "../malakal-widget" }
eframe = "0.16.0"
chrono = "0.4.19"
derive_builder = "0.10.2"
