[package]
name = "malakal-app"
version = "0.1.0"
edition = "2021"

# optimize dependencies for debug builds
[profile.dev.package."*"]
opt-level = 2

[dependencies]
eframe = "0.16.0"
chrono = "0.4.19"
chrono-tz = "0.6.1"
derive_builder = "0.10.2"
intervaltree = "0.2.7"
uuid = { version = "0.8.2", features = ["v4"] }
# only for ics generation
ics = "0.5.7"
# only for ics parsing
ical = { version = "0.7.0", features = ["ical"] }

# for webdav support (work in progress)
# kitchen-fridge = { git = "https://github.com/shouya/kitchen-fridge.git" }

rusqlite = {version = "0.26.3", features = ["chrono"] }
anyhow = { version = "1.0.53", features = ["backtrace"] }
log = "0.4.14"
env_logger = "0.9.0"
regex = "1.5.4"
