[package]
name = "malakal-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.16.0"
chrono = "0.4.19"
derive_builder = "0.10.2"
intervaltree = "0.2.7"
uuid = { version = "0.8.2", features = ["v4"] }
icalendar = { version = "0.11.0", features = ["parser"] }
